name: pylint

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main
    
jobs:
    pylint:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                find . -name "requirements.txt" -exec pip install -r {} \;
                pip install pylint
            
            - name: Run Pylint
              run: |
                pylint **/*.py
                
