name: Terraform Validate

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - terraform/ECR
          - terraform/dashboard
          - terraform/pipeline_live_data
          - terraform/pipeline_archived_data

    name: Validate ${{ matrix.directory }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate
    
      - name: Terraform Format
        run: terraform fmt -recursive
